### ISSUE TITLE
Specify technology used

### ISSUE THREAD

**Issue by jaime-olivares** [chafey/dicomWeb#1]
I suggest to specify the core technologies used on each product (programming language, web engine, database engine, etc.)

**Comment by mishrapw** [comment]
Hi @jaime-olivares,
It's all depend up on vendor choice, but as per my opinion technology would be
WADO Client: HTML5 with Bootstrap or Foundation CSS
WADO Server: by using HTTP GET & POST method 
- ASP.Net Web API Restful Service 
- C# WCF Rest Services
- Java Web Restful Services

@chafey correct me if am wrong.

I already started working on this, will share code once it done.

-Pawan

**Comment by jaime-olivares** [comment]
@mishrapw I refer to the list of dicomweb products presented in this page. Each one has a specific technology set used.

**Comment by mishrapw** [comment]
Sorry @jaime-olivares, i was in other page.

For your info only
- dcm4chee is Java Restful Service.
- Orthanc is C++ based Service DLL.
- Simple QIDO is .Net Web API.

don't know about commercial tools.

**Comment by RkReddy88** [comment]
Hi @mishrapw ,
Can you please share the code for the implementation as you have said.
